absendulu/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from .views import ProfileView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('attendance/', include('attendance.urls')),
    path('accounts/profile/', ProfileView.as_view(), name='account_profile'),
]

attendance/urls.py
from django.urls import path
from .views import (
    GroupCreateView,
    GroupListView,
    GroupUpdateView,
    GroupDeleteView,
    JoinGroupView,
    ReportCreateView,
    ReportListView,
    RecordCreateView,
    GroupDetailView,
    MeetingListView,
    RecordListView,
    GroupLeaveView
)

urlpatterns = [
    path('groups', GroupListView.as_view(), name='group_list'),
    path('groups/create', GroupCreateView.as_view(), name='group_create'),
    path('groups/update/<slug:pk>',
         GroupUpdateView.as_view(), name='group_update'),
    path('groups/delete/<slug:group_pk>',
         GroupDeleteView.as_view(), name='group_delete'),
     path('groups/leave/<slug:group_pk>',
         GroupLeaveView.as_view(), name='group_leave'),
    path('groups/join',
         JoinGroupView.as_view(), name='group_join'),
    path('groups/<slug:group_pk>/reports/create',
         ReportCreateView.as_view(), name='report_create'),
    path('groups/<slug:group_pk>/reports',
         ReportListView.as_view(), name='report_list'),
    path('groups/<slug:group_pk>/meetings',
         MeetingListView.as_view(), name='meeting_list'),
    path('groups/<slug:pk>', GroupDetailView.as_view(), name='group_detail'),
    path('groups/attend/<slug:report_pk>',
         RecordCreateView.as_view(), name='record_create'),
    path('report/<slug:report_pk>',
         RecordListView.as_view(), name='record_list'),
]

attendance/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.conf import settings
from django.urls import reverse
import uuid

fs = FileSystemStorage(location=settings.MEDIA_ROOT)


class Group(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    code = models.CharField(max_length=50, blank=True, null=True, unique=True)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='members',
        blank=True
    )
    admins = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='admins',
        blank=True
    )

    def __str__(self):
        return f'{self.pk} - {self.name}'

    def get_absolute_url(self):
        return reverse('group_detail', args=[self.pk])

    def get_update_url(self):
        return reverse('group_update', args=[self.pk])

    def get_delete_url(self):
        return reverse('group_delete', args=[self.pk])


class Report(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.pk} - {self.name}'


class Record(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    photo = models.ImageField(
        storage=fs, upload_to='attendance_records', blank=True)
    time = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=100, blank=True)
    report = models.ForeignKey(
        Report, related_name='records', on_delete=models.CASCADE, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'{self.pk} - {self.user.username}'

attendance/forms.py
from django import forms
from .models import Group, Report, Record


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'description']


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['name', 'description']


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['location']


class JoinGroupForm(forms.BaseForm):
    class Meta:
        fields = ['code']

attendance/views.py
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    View,
    DetailView,
    FormView,
    TemplateView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from .models import Group, Record, Report
from .forms import GroupForm, ReportForm, RecordForm
from django.urls import reverse
from django.db.models import Q
import uuid
import base64
import io
from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile


class GroupCreateView(LoginRequiredMixin, CreateView):
    form_class = GroupForm
    template_name = 'attendance/group_form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.code = str(uuid.uuid4())
        instance.is_approved = True
        instance.save()
        instance.admins.add(self.request.user)
        return super().form_valid(form)


class GroupListView(ListView):
    model = Group
    template_name = 'attendance/group_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset()
        queryset = queryset.filter(Q(admins=user) | Q(members=user))
        return queryset.prefetch_related('admins', 'members')


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'attendance/group_form.html'


class GroupDeleteView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        group = Group.objects.get(pk=self.kwargs['group_pk'])
        report = Report.objects.filter(group=group)
        if report.exists():
            report.delete()
        group.delete()
        return redirect('group_list')

class GroupLeaveView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        user = self.request.user
        group = Group.objects.get(pk=self.kwargs['group_pk'])
        group.members.remove(user)
        return redirect('group_list')

class ReportCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = ReportForm
    template_name = 'attendance/report_form.html'

    def form_valid(self, form):
        group_pk = self.kwargs['group_pk']
        group = Group.objects.get(pk=group_pk)
        form.instance.group = group
        return super().form_valid(form)

    def test_func(self):
        group_pk = self.kwargs['group_pk']
        user = self.request.user
        admins = Group.objects.get(pk=group_pk).admins
        return admins.filter(pk=user.pk).exists()

    def get_success_url(self):
        group_pk = self.kwargs['group_pk']
        return reverse('report_list', args=[group_pk])


class ReportListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Report
    template_name = 'attendance/report_list.html'

    def get_queryset(self):
        group_pk = self.kwargs['group_pk']
        queryset = super().get_queryset()
        queryset = queryset.prefetch_related('group').filter(group=group_pk)
        return queryset

    def test_func(self):
        group_pk = self.kwargs['group_pk']
        user = self.request.user
        admins = Group.objects.get(pk=group_pk).admins
        return admins.filter(pk=user.pk).exists()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_pk = self.kwargs['group_pk']
        context['group'] = Group.objects.get(pk=group_pk)
        return context


class MeetingListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Report
    template_name = 'attendance/meeting_list.html'

    def get_queryset(self):
        group_pk = self.kwargs['group_pk']
        queryset = super().get_queryset()
        queryset = queryset.prefetch_related('group').filter(group=group_pk)
        return queryset

    def test_func(self):
        group_pk = self.kwargs['group_pk']
        user = self.request.user
        members = Group.objects.get(pk=group_pk).members
        return members.filter(pk=user.pk).exists()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_pk = self.kwargs['group_pk']
        user = self.request.user
        context['group'] = Group.objects.get(pk=group_pk)
        record_list = Record.objects.filter(
            user=user).values_list('report', flat=True)
        context['attended'] = record_list
        print(record_list)
        return context


class RecordCreateView(LoginRequiredMixin, FormView):
    model = Record
    form_class = RecordForm
    template_name = 'attendance/record_form.html'

    def post(self, request, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        report_pk = kwargs['report_pk']
        report = Report.objects.get(pk=report_pk)
        user = request.user
        _, img_data = str(request.POST.get('photo')).split(',')
        img = decodeImage(img_data)
        img_io = io.BytesIO()
        img.save(img_io, format='PNG')
        if form.is_valid():
            form.instance.photo = InMemoryUploadedFile(
                img_io,
                field_name=None,
                name=str(uuid.uuid4())+'.png',
                content_type='image/png',
                size=img_io.tell,
                charset=None)
            form.instance.report = report
            form.instance.user = user
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('group_list')


class JoinGroupView(LoginRequiredMixin, TemplateView):
    template_name = 'attendance/join_group.html'

    def post(self, request, **kwargs):
        code = request.POST['code']
        user = request.user
        group = Group.objects.get(code=code)
        group.members.add(user)
        return redirect(reverse('group_list'))


class RecordListView(LoginRequiredMixin, ListView):
    model = Record
    template_name = 'attendance/record_list.html'

    def get_queryset(self):
        report_pk = self.kwargs['report_pk']
        return super().get_queryset().filter(report=report_pk)


class GroupDetailView(LoginRequiredMixin, DetailView):
    model = Group
    template_name = 'attendance/group_detail.html'

    def get_queryset(self):
        return super().get_queryset().prefetch_related('members', 'admins')


class ReportDetailView(LoginRequiredMixin, ListView):
    model = Report


def decodeImage(data):
    try:
        data = base64.b64decode(data.encode('UTF-8'))
        buf = io.BytesIO(data)
        img = Image.open(buf)
        return img
    except IOError:
        return None

templates/attendance/group_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Group Detail | Absendulu{% endblock %}
{% block css %}
<link href="{% static 'css/register.css' %}"
      rel="stylesheet">
{% endblock css %}
{% block content %}

<div class="container py-5 my-5">
    <div class="card m-auto">
        <div class="card-header p-4"
             style="background-color: #24355C;">
            <h4 class="card-title text-center text-white">Attendance Group</h4>
        </div>
        <div class="card-body">
            <div class="md-form input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon"
                          id="material-addon1">
                        <i class="fas fa-users"></i>
                    </span>
                </div>
                <input type="text"
                       name="name"
                       maxlength="50"
                       required
                       id="id_name"
                       class="form-control"
                       placeholder="Group Name"
                       aria-label="Group Name"
                       aria-describedby="material-addon1"
                       value='{{ object.name }}'
                       readonly>
            </div>

            <div class="md-form input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon">
                        <i> </i>
                    </span>
                </div>
                <textarea name="description"
                          cols="40"
                          rows="10"
                          maxlength="200"
                          required
                          id="id_description"
                          placeholder="{{ object.description }}"
                          class="md-textarea form-control"
                          readonly></textarea>
            </div>

            <div class="md-form input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon">
                        <i class="fas fa-key"></i>
                    </span>
                </div>
                <input type="text"
                       name="code"
                       maxlength="30"
                       id="id_code"
                       class="form-control"
                       placeholder="Group Code"
                       aria-label="Group Code"
                       value='{{ object.code }}'
                       readonly>
            </div>
            {% if user in object.admins.all %}
            <hr>
            <div class="mx-5">
                <h2>Members</h2>
                <ul class="mt-3">
                    {% for member in object.members.all %}
                    <li>{{ member.get_full_name }}</li>
                    {% empty %}
                    <p class="text-muted">This group does not have any member.</p>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

templates/attendance/group_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create Group | Absendulu{% endblock %}
{% block css %}
<link href="{% static 'css/register.css' %}"
      rel="stylesheet">
{% endblock css %}
{% block content %}

<div class="container py-5 my-5">
    <form class="card m-auto"
          method="POST"
          action="/attendance/groups/create">
        <div class="card-header p-4"
             style="background-color: #24355C;">
            <h4 class="card-title text-center text-white">Create Attendance Group</h4>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <div class="md-form input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon"
                          id="material-addon1">
                        <i class="fas fa-users"></i>
                    </span>
                </div>
                <input type="text"
                       name="name"
                       maxlength="50"
                       required
                       id="id_name"
                       class="form-control"
                       placeholder="Group Name"
                       aria-label="Group Name"
                       aria-describedby="material-addon1">
            </div>

            <div class="md-form input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon">
                        <i> </i>
                    </span>
                </div>
                <textarea name="description"
                          cols="40"
                          rows="10"
                          maxlength="200"
                          required
                          id="id_description"
                          placeholder="Please describe this attendance group..."
                          class="md-textarea form-control"></textarea>
            </div>

        </div>
        <div class="card-footer">
            <button class="btn btn-info btn-block my-4"
                    type="submit">Submit</button>
        </div>
    </form>
</div>

{% endblock content %}

templates/attendance/group_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Group List | Absendulu{% endblock title %}

{% block content %}
<div class="container py-5 my-5">
    <div class="table-responsive text-nowrap">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Group Name</th>
                    <th>Description</th>
                    <th class="text-right">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>{{ object.description }}</td>
                    <td class="text-right">
                        {% if user in object.admins.all %}
                        <a href="{% url 'report_list' group_pk=object.pk %}"
                           class="btn btn-sm btn-white">
                            Reports
                        </a>
                        <a>
                        <form method="POST" action="{% url 'group_delete' group_pk=object.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-danger"
                                    type="submit">Delete</button>
                        </form>
                        </a>
                        {% else %}
                        <a href="{% url 'meeting_list' group_pk=object.pk %}"
                           class="btn btn-sm btn-success">
                            Meeting List
                        </a>
                        <form method="POST" action="{% url 'group_leave' group_pk=object.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-danger"
                                    type="submit">Leave</button>
                        </form>
                        {% endif %}               
                        <a href="{% url 'group_detail' object.id %}"
                           class="btn btn-sm btn-info">
                            Details
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/attendance/join_group.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Join Group | Absendulu{% endblock %}
{% block css %}
<link href="{% static 'css/register.css' %}"
      rel="stylesheet">
{% endblock css %}
{% block content %}


<div class="wrapper">
    <form class="signup"
          id="joingroup_form"
          method="post"
          action="{% url 'group_join' %}">
        {% csrf_token %}
        <div class="header">
            <p class="h4 mb-4 py-5 text-center">Join a Group</p>
        </div>
        <form action="{% url 'group_join' %}"
              method="post">
            <div class="inputBody">

                <div class="inputForm">
                    <i class="fas fa-user prefix grey-text"></i>
                    <input type="text"
                           name="code"
                           class="form-control mb-4"
                           placeholder="Enter Group Code here">
                </div>

                <button class="btn btn-info btn-block my-4"
                        type="submit">Join Group</button>

            </div>
        </form>
    </form>
</div>

{% endblock content %}

templates/attendance/meeting_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Meeting List | Absendulu{% endblock title %}

{% block css%}
<link href="{% static 'css/grouplistmain.css' %}"
      rel="stylesheet">
<link href="{% static 'css/grouplistutils.css' %}"
      rel="stylesheet">
{% endblock css %}

{% block content %}

<h1 class="text-center pt-4">
    {{ group.name }} Meeting List
</h1>

<div class="container py-2 my-5">
    <div class="table-responsive text-nowrap">
        <table class="table table-stripped">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th class="text-right">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>{{ object.description }}</td>
                    {% if not object.id in attended %}
                    <td class="text-right">
                        <a href="{% url 'record_create' report_pk=object.pk %}"
                           class="btn btn-success">
                            Attend
                        </a>
                    </td>
                    {% else %}
                    <td class="text-right">
                        Attended
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/attendance/record_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Attendance Form | Absendulu{% endblock %}

{% block css %}
<link href="{% static 'css/register.css' %}"
      rel="stylesheet">
<link href="{% static 'css/profile.css' %}"
      rel="stylesheet">
<link href="{% static 'css/attendanceform.css' %}"
      rel="stylesheet">
{% endblock css %}

{% block content %}
</a>
<!-- TODO: tolong dirapikan -->
<section class="intro-section"
         style="background-image: url({% static 'img/bg-profile.jpg' %});">
    <div class="wrapper">

        <div class="inputBody">
            <div class="camera">
                <video id="video">Video stream not available.</video>
                <button class="btn btn-default btn-rounded"
                        id="startbutton">Take photo</button>
            </div>
            <canvas id="canvas">
            </canvas>

            <button class="btn btn-default btn-rounded"
                    onclick="getLocation()"
                    id="loc-id"
                    name="location">
                Pin Live Location
            </button>

            <hr>
            <form method="POST"
                  id="att-form">
                {% csrf_token %}
                <p>Your Location</p>
                <input type="text"
                       id="show-loc-id"
                       name="location">
                <p>Your Photo</p>
                <div class="output">
                    <img id="photo">
                    <input type="text"
                           id="b64photo"
                           name="photo"
                           hidden>
                </div>
                <input type="submit"
                       class="btn btn-info btn-block my-4"
                       value="Submit Attendance">
            </form>
        </div>
    </div>


    <script>
        var x = document.getElementById("loc-id");

        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                x.innerHTML = "Geolocation is not supported by this browser.";
            }
        }

        function showPosition(position) {
            x.value = "Latitude: " + position.coords.latitude +
                "<br>Longitude: " + position.coords.longitude;
            document.getElementById("show-loc-id").value = "Latitude: " + position.coords.latitude +
                " Longitude: " + position.coords.longitude;
        }

        (function() {
            console.log();
            // The width and height of the captured photo. We will set the
            // width to the value defined here, but the height will be
            // calculated based on the aspect ratio of the input stream.

            var width = 320; // We will scale the photo width to this
            var height = 0; // This will be computed based on the input stream

            // |streaming| indicates whether or not we're currently streaming
            // video from the camera. Obviously, we start at false.

            var streaming = false;

            // The various HTML elements we need to configure or control. These
            // will be set by the startup() function.

            var video = null;
            var canvas = null;
            var photo = null;
            var startbutton = null;

            function startup() {
                video = document.getElementById('video');
                canvas = document.getElementById('canvas');
                photo = document.getElementById('photo');
                startbutton = document.getElementById('startbutton');

                navigator.mediaDevices.getUserMedia({
                        video: true,
                        audio: false
                    })
                    .then(function(stream) {
                        video.srcObject = stream;
                        video.play();
                    })
                    .catch(function(err) {
                        console.log("An error occurred: " + err);
                    });

                video.addEventListener('canplay', function(ev) {
                    if (!streaming) {
                        height = video.videoHeight / (video.videoWidth / width);

                        // Firefox currently has a bug where the height can't be read from
                        // the video, so we will make assumptions if this happens.

                        if (isNaN(height)) {
                            height = width / (4 / 3);
                        }

                        video.setAttribute('width', width);
                        video.setAttribute('height', height);
                        canvas.setAttribute('width', width);
                        canvas.setAttribute('height', height);
                        streaming = true;
                    }
                }, false);

                startbutton.addEventListener('click', function(ev) {
                    takepicture();
                    ev.preventDefault();
                }, false);

                clearphoto();
            }

            // Fill the photo with an indication that none has been
            // captured.

            function clearphoto() {
                var context = canvas.getContext('2d');
                context.fillStyle = "#AAA";
                context.fillRect(0, 0, canvas.width, canvas.height);

                var data = canvas.toDataURL('image/png');
                photo.setAttribute('src', data);
                document.getElementById('b64photo').value = data;
            }

            // Capture a photo by fetching the current contents of the video
            // and drawing it into a canvas, then converting that to a PNG
            // format data URL. By drawing it on an offscreen canvas and then
            // drawing that to the screen, we can change its size and/or apply
            // other changes before drawing it.

            function takepicture() {
                var context = canvas.getContext('2d');
                if (width && height) {
                    canvas.width = width;
                    canvas.height = height;
                    context.drawImage(video, 0, 0, width, height);

                    var data = canvas.toDataURL('image/png');
                    photo.setAttribute('src', data);
                    document.getElementById('b64photo').value = data;
                } else {
                    clearphoto();
                }
            }

            // Set up our event listener to run the startup process
            // once loading is complete.
            window.addEventListener('load', startup, false);
        })();
    </script>
</section>
{% endblock content %}

templates/attendance/record_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Record | Absendulu{% endblock title %}

{% block css%}
<link href="{% static 'css/grouplistmain.css' %}"
      rel="stylesheet">
<link href="{% static 'css/grouplistutils.css' %}"
      rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="container py-5 my-5">
    <div class="table-responsive text-nowrap">
        <table class="table table-stripped">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Time</th>
                    <th>Location</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.user.get_full_name }}</td>
                    <td>{{ object.time }}</td>
                    <td>{{ object.location }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/attendance/report_form.html
{% extends 'base.html' %}

{% block title %} Create Attendance | Absendulu {% endblock title %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <form class="card m-auto"
          method="POST">
        <div class="card-header p-4"
             style="background-color: #24355C;">
            <h4 class="card-title text-center text-white">Create Report</h4>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <div class="md-form input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon"
                          id="material-addon1">
                        <i class="fas fa-users"></i>
                    </span>
                </div>
                <input type="text"
                       name="name"
                       maxlength="50"
                       required
                       id="id_name"
                       class="form-control"
                       placeholder="Report Name"
                       aria-label="Group Name"
                       aria-describedby="material-addon1">
            </div>

            <div class="md-form input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text md-addon">
                        <i> </i>
                    </span>
                </div>
                <textarea name="description"
                          cols="40"
                          rows="10"
                          maxlength="200"
                          required
                          id="id_description"
                          placeholder="Please describe this report..."
                          class="md-textarea form-control"></textarea>
            </div>

        </div>
        <div class="card-footer">
            <button class="btn btn-info btn-block my-4"
                    type="submit">Submit</button>
        </div>
    </form>
</form>

{% endblock content %}